cursor            #ffb3b0
cursor_text_color #571d1d

foreground            #f0dedd
background            #140c0c
selection_foreground  #442928
selection_background  #e7bdba
url_color             #e7bdba

#: black 000000 767676
color0  #1a1111
color8  #3d3232
#: red cc0403 f2201f
color1  #260408
color9  #b11225
#: green 19cb00 23fd00
color2  #e7bdba
color10 #ffdad8
#: yellow cecb00 fffd00
color3  #e3c28c
color11 #ffdea9
#: blue 0d73cc 1a8fff
color4  #733332
color12 #ffb3b0
#: magenta cb1ed1 fd28ff
color5  #5d3f3e
color13 #e7bdba
#: cyan 0dcdcd 14ffff
color6  #594319
color14 #e3c28c
#: white dddddd ffffff
color7  #d7c1c0
color15 #f0dedd

mark1_foreground #3b080a
mark1_background #ffdad8
mark2_foreground #2c1514
mark2_background #ffdad8
mark3_foreground #271900
mark3_background #ffdea9

active_tab_foreground #571d1d
active_tab_background #ffb3b0
inactive_tab_foreground #ffdad8
inactive_tab_background #733332

active_border_color #ffb3b0
inactive_border_color #571d1d
# bell_border_color #ff5a00