general {
    ignore_empty_input = true
    hide_cursor = true
}

background {
    monitor =
    path = /home/zync/.config/themes/delete/wallpapers/01.jpg
    color = 0xff131318
    blur_passes = 3
}

animations {
    enabled = true
}

input-field {
    monitor =
    size = 650, 100
    position = 0, 0
    halign = center
    valign = center

    inner_color = 0xff131318
    outer_color = 0xffc2c1ff
    font_color = 0xffe5e1e9

    outline_thickness = 4
    font_family = JetBrainsMono Nerd Font

    placeholder_text = Enter Password
    check_color = 0xffc2c1ff
    fail_text = <i>$FAIL ($ATTEMPTS)</i>

    rounding = 0
    shadow_passes = 0
    fade_on_empty = false
}

auth {
    fingerprint:enabled = false
}
