#!/bin/bash

COLORS="$HOME/.config/hypr/colors.lua"
HYPRLOCK="$HOME/.config/hypr/hyprlock.conf"

wallpaper=$(lua -e "print(dofile('$COLORS').image)")
background=$(lua -e "print(dofile('$COLORS').surface)")
primary=$(lua -e "print(dofile('$COLORS').primary)")
on_surface=$(lua -e "print(dofile('$COLORS').on_surface)")

cat > "$HYPRLOCK" <<EOF
general {
    ignore_empty_input = true
    hide_cursor = true
}

background {
    monitor =
    path = $wallpaper
    color = $background
    blur_passes = 3
}

animations {
    enabled = true
}

input-field {
    monitor =
    size = 650, 100
    position = 0, 0
    halign = center
    valign = center

    inner_color = $background
    outer_color = $primary
    font_color = $on_surface

    outline_thickness = 4
    font_family = JetBrainsMono Nerd Font

    placeholder_text = Enter Password
    check_color = $primary
    fail_text = <i>\$FAIL (\$ATTEMPTS)</i>

    rounding = 0
    shadow_passes = 0
    fade_on_empty = false
}

auth {
    fingerprint:enabled = false
}
EOF